### ISSUE TITLE
Regarding hk.transform_with_state

### ISSUE THREAD

**Issue by MichaelMMeskhi** [alexOarga/haiku-geometric#2]
When doing:

```python
@hk.without_apply_rng
@hk.transform_with_state
def model(graph):
    return GCN()(graph)
```

Doing `logits, state = model.apply(params, state, graph)` gives an error:

`TypeError: params argument does not appear valid. It should be a mapping but is of type <class 'tuple'>. For reference the parameters for apply are apply(params, rng, ...) for hk.transform and apply(params, state, rng, ...) for hk.transform_with_state`

**Comment by alexOarga** [comment]
Hi,

Thank you for raising this issue. Unfortunately, I haven't been able to reproduce this error.
Could you please provide a code snippet showing how the model is initialized?
Also, `params` seems to be a tuple, instead of the expected dict. You may want to check the elements of the tuple to get more information. Maybe this helps.

**Comment by MichaelMMeskhi** [comment]
Hi @alexOarga, thank you for responding. I apologize but this error was unrelated to your code and an issue on my end.
